layer.conf: fix LAYERDEPENDS_qt6-layer
* qtgrpc depends on protobuf from meta-oe:

  ERROR: Nothing PROVIDES 'protobuf-native' (but /OE/build/oe-core/meta-qt6/recipes-qt/qt6/qtgrpc_git.bb DEPENDS on or otherwise requires it). Close matches:
    popt-native
    xcb-proto-native
    xorgproto-native
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'qtgrpc', 'protobuf-native']

* and qtpdf, qtwebengine depend python3-html5lib-native on from meta-python:

  ERROR: Nothing PROVIDES 'python3-html5lib-native' (but /OE/build/oe-core/meta-qt6/recipes-qt/qt6/qtpdf_git.bb, /OE/build/oe-core/meta-qt6/recipes-qt/qt6/qtwebengine_git.bb DEPENDS on or otherwise requires it). Close matches:
    python3-toml-native
    python3-tomli-native
    python3-urllib3-native
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'qtpdf', 'python3-html5lib-native']

Change-Id: I616e03e3a259e532e4ccd6ec87a2975c063837fc
Reviewed-by: Martin Jansa <Martin.Jansa@gmail.com>
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>
(cherry picked from commit 2713f52a6f178d5a985ba8a21d6e9383b71b5030)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 6270297ae730f5dac906946e55b9b0697433cbdd)