qt3d,qtquick3d: define IOAPI_NO_64
In yocto we can safely assume 64bit off_t as LFS is default, this helps
compile with musl which does not provide the legacy *64 APIs anymore

Fixes

src/3rdparty/assimp/src/contrib/unzip/ioapi.c:24:29: error: implicit declaration of function 'ftello'; did you mean 'ftell'? [-Wimplicit-function-declaration]
|    24 | #define FTELLO_FUNC(stream) ftello64(stream)
|       |                             ^~~~~~~~

Change-Id: I0a03b833027c55fe2d4fc1af78c5cc78f636eaff
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>