Coin: fetch repo from github
Git clones from google fail frequently with:
   >> fatal: early EOF
   >> error: index-pack died
Switch to using github mirror for the git-repo repository.

Change-Id: Id0cbf3c59e50869d62880e56251b003490c4c1ee
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
(cherry picked from commit 61f984c49d495a00e944ccc437447782afeb8ec0)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>