qtbase: workaround GCC15 issue with stdckdint.h header
Change 08ebe3465cc2fce98662b5833b75503490f66265 in qtbase enabled
support for C23/C++26 <stdckdint.h>.
Similar to GCC14 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=121811),
GCC15 has problem using stdckdint.h in Yocto setup as default include
paths are ordered so that the C header is found first.

| nativesdk-qtbase/6.11.0/sources/qtbase-6.11.0/src/corelib/global/qnumeric.h: In function 'constexpr std::enable_if_t<((bool)is_unsigned_v<T>), bool> qAddOverflow(T, T, T*)':
| nativesdk-qtbase/6.11.0/sources/qtbase-6.11.0/src/corelib/global/qnumeric.h:282:12: error: '_Bool' was not declared in this scope [-Wtemplate-body]
|   282 |     return ckd_add(r, v1, v2);
|       |            ^~~~~~~

As a workaround, disable the feature until better solution
is found.

Change-Id: I0eeeb8bc97411646a7ccc71aa38f5d6fe8a6e16a
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>