webengine: add patch for python 3.11 build issue
yocto master branch updated python to 3.11, resulting
in webengine build error(s):

"File "/home/qt/work/build/build/tmp/work/cortexa15t2hf-neon-poky-linux-gnueabi/qtwebengine/6.4.1-r0/git/src/3rdparty/chromium/tools/grit/grit/util.py", line 214, in ReadFile
with io.open(filename, mode, encoding=encoding) as f:
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'"

Add patch from chromium upstream.

Change-Id: I6308d2acd17a74b20ad6651d59f34e7246dc96ef
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>
(cherry picked from commit 676e6da41b8ed42ce32a6b85fac792413bd2a35f)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>