pyside6: workaround big.LITTLE architectures
Compiler flags are passed to shiboken which uses those with clang.
GCC supports big.LITTLE architecture TUNEs (cortex-a72.cortex-a53)
that clang does not. This causes some targets to fail with
    error: unsupported argument 'cortex-a72.cortex-a53+crc+crypto' to option '-mcpu='

Workaround this by replacing big.LITTLE mcpu args with LITTLE only.
Follows similar workaround done in meta-clang when clang toolchain is used.

Change-Id: I4042cbfb1d48b940539ec970058025ea0b2be937
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>