qtinterfaceframework: fix example packaging
Multiple examples provide the same library which causes packaging failure:
ERROR: qtinterfaceframework-6.4.0-r0 do_package: qtinterfaceframework-examples: Multiple shlib providers for libInstrumentCluster.so

Add the library to PRIVATE_LIBS, since it's only used by the examples.

Change-Id: If09bc7d235171b2b844ec579f6affa6fbe3f8a6d
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
(cherry picked from commit 90a8c72bedb631d3c73adf0ebb2e5c99d6df43e1)