python3-qface: update 2.0.4 -> 2.0.11
Required for latest qtinterfaceframework. Fixes build issue:

"/home/qt/work/build/build/tmp/work/core2-64-poky-linux/qtinterfaceframework/6.5.7-r0/recipe-sysroot-native/usr/lib/python3.8/site-packages/qface/utils.py", line 22, in load_filters
|     exec(path.text(), ctx)
| AttributeError: 'PosixPath' object has no attribute 'text'"

Pick-to: 6.2
Change-Id: I9a407553f7546344a49020b8ebf04540a73fbf0c
Reviewed-by: Jani Heikkinen <jani.heikkinen@qt.io>