coin: skip mysql on kirkstone
Disable sql-mysql when using kirkstone to avoid mariadb-native
build failure with GCC13 when using Ubuntu 24.04 VM.

"build/tmp/work/x86_64-linux/mariadb-native/10.7.8-r0/mariadb-10.7.8/storage/rocksdb/rocksdb/db/compaction/compaction_iteration_stats.h:23:3: error: ‘uint64_t’ does not name a type"

Pick-to: 6.5
Change-Id: Ib40a892713d09f55bae56814b2cec6dcc76a360e
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>
(cherry picked from commit d807bd38a39b6f5e7c7c964980752c5353573019)