python3-qface: backport recipe from meta-oe master
Latest qtinterfaceframework requires qface version 2.0.11. Meta-qt6
layer used to have it some time ago, but it was moved to meta-python under
meta-openembedded. Only meta-openembedded(master) branch has required version
available currently.

Backport the recipe from meta-openembedded(master) branch:
https://git.openembedded.org/meta-openembedded/tree/meta-python/recipes-devtools/python/python3-qface_2.0.11.bb

Fixes build issue:
|   File "/home/qt/work/build/build/tmp/work/core2-32-poky-linux/qtinterfaceframework/6.7.3/recipe-sysroot-native/usr/lib/python3.11/site-packages/qface/utils.py", line 22, in load_filters
|     exec(path.text(), ctx)
|          ^^^^^^^^^
| AttributeError: 'PosixPath' object has no attribute 'text'

Change-Id: If3ba64fac1375452cba031358e67fd90b3331ba2
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>
(cherry picked from commit f52437ef0a9609b577d3309b3bbca233bab230bc)
Reviewed-by: Jani Heikkinen <jani.heikkinen@qt.io>