libarchive: update upstream patch
Openembedded-core(master) added libarchive patch from an open github PR
[https://github.com/libarchive/libarchive/pull/2846] causing mingw32 CI issue.
Override the oe-core patch with a working latest version of the PR commit/patch.

Fixes issue:
"
 ../sources/libarchive-3.8.9/libarchive/archive_read_support_format_rpm.c: In function 'rpm_strndup':
 ../sources/libarchive-3.8.9/libarchive/archive_read_support_format_rpm.c:1052:16: error: implicit declaration of function 'strndup' [-Wimplicit-function-declaration]
  1052 |         return strndup(s, len);
       |                ^~~~~~~
 ../sources/libarchive-3.8.9/libarchive/archive_read_support_format_rpm.c:1052:16: warning: incompatible implicit declaration of built-in function 'strndup' [-Wbuiltin-declaration-mismatch]
 make[1]: *** [Makefile:7886: libarchive/archive_read_support_format_rpm.lo] Error 1
"

Task-number: QTBUG-151141
Change-Id: Ied9e0e2e37503bed4f22092ef05620faec85faa5
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>