qtpdf: add cups dependency
QtPDF depends on cups-config during 'bitbake <image> -c populate_sdk'.

Without this patch the build fails with:
 FileNotFoundError: [Errno 2] No such file or directory: 'cups-config'

Signed-off-by: Christoph Fritz <chf.fritz@googlemail.com>
Fixes: QTBUG-126996
Pick-to: 6.8
Change-Id: I28b47687159717b468373a32303447f80063d3cf
Reviewed-by: Ari Parkkila <ari.parkkila@qt.io>